Upgrade to TypeScript 5.9 (#66)
From [Announcing TypeScript
5.9](https://devblogs.microsoft.com/typescript/announcing-typescript-5-9/#notable-behavioral-changes):

> One notable change is that ArrayBuffer has been changed in such a way
that it is no longer a supertype of several different TypedArray types.
This also includes subtypes of UInt8Array, such as Buffer from Node.js.
As a result, you’ll see new error messages such as:

```
error TS2345: Argument of type 'ArrayBufferLike' is not assignable to parameter of type 'BufferSource'.
error TS2322: Type 'ArrayBufferLike' is not assignable to type 'ArrayBuffer'.
error TS2322: Type 'Buffer' is not assignable to type 'Uint8Array<ArrayBufferLike>'.
error TS2322: Type 'Buffer' is not assignable to type 'ArrayBuffer'.
error TS2345: Argument of type 'Buffer' is not assignable to parameter of type 'string | Uint8Array<ArrayBufferLike>'.
```

> If you encounter issues with Buffer, you may first want to check that
you are using the latest version of the @types/node package. This might
include running

```
npm update @types/node --save-dev
```

> Much of the time, the solution is to specify a more specific
underlying buffer type instead of using the default `ArrayBufferLike`
(i.e. explicitly writing out `Uint8Array<ArrayBuffer>` rather than a
plain `Uint8Array`). In instances where some `TypedArray` (like
`Uint8Array`) is passed to a function expecting an `ArrayBuffer` or
`SharedArrayBuffer`, you can also try accessing the buffer property of
that `TypedArray` like in the following example:

```diff
  let data = new Uint8Array([0, 1, 2, 3, 4]);
- someFunc(data)
+ someFunc(data.buffer)
```

This PR upgrades us to TypeScript 5.9:

* According to `.nvmrc`, we do run Node 24. So I'm upgrading
`@types/node` to version `24.2.0`, the latest version. This follows
their suggestion to update to the latest `@types/node`.
* I'm following the suggestion to use a more specific underlying buffer
type by replacing `ArrayBuffer` with `Uint8Array`. Note that NodeJS's
`Buffer` class extends `Uint8Array`, so this works with the Buffer types
we've been handling as well
* I've tested to make sure we're still rendering images!